version: "3.4"
services:
  db:
    image: "postgres:${DA_POSTGRES_VERSION:-11.2}"
    container_name: toolbox_db
    volumes:
      - ./${DA_DB_VOLUME_NAME:-db}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DA_DB_USERNAME:-toolbox}
      - POSTGRES_PASSWORD=${DA_DB_PASSWORD:-1312}
      - POSTGRES_DB=${DA_DB_DATABASE:-toolbox_dev}

  dbtest:
    image: "postgres:${DA_POSTGRES_VERSION:-11.2}"
    container_name: dbtest
    environment:
      - POSTGRES_USER=${DA_DB_USERNAME:-toolbox}
      - POSTGRES_PASSWORD=${DA_DB_PASSWORD:-1312}
      - POSTGRES_DB=${DA_DB_DATABASE:-toolbox_dev}
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: mix.Dockerfile
    container_name: toolbox
    volumes:
      - ./config:/app/config
      - ./lib:/app/lib
      - ./priv:/app/priv
      - ./rel:/app/rel
      - ./test:/app/test
      - ./mix.exs:/app/mix.exs
      - ./mix.lock:/app/mix.lock
      - ./.formatter.exs:/app/.formatter.exs
      - ./build:/app/_build
      - ./deps:/app/deps
    ports:
      - "1312:1312"
    command: >
      /bin/sh -c "/bin/wait-for db:5432 -- mix deps.get && mix phx.server"
    # DB_HOSTNAME value MUST match the name of the db service!
    # DA_DB_HOSTNAME_TEST value MUST match the name of the test db service!
    environment:
      - POSTGRES_USER=${DA_DB_USERNAME:-toolbox}
      - POSTGRES_PASSWORD=${DA_DB_PASSWORD:-1312}
      - POSTGRES_DB=${DA_DB_DATABASE:-toolbox_dev}
      - POSTGRES_HOST=${DA_DB_HOSTNAME_DEV:-db}
      - POSTGRES_PORT=${DA_DB_PORT_DEV:-5432}
      - DB_HOSTNAME_TEST=${DA_DB_HOSTNAME_TEST:-dbtest}
      - PORT=1312
      - ENV=dev
    depends_on:
      - db
      - dbtest
      
volumes:
  db:
    name: ${DA_DB_VOLUME_NAME:-db}
    external: ${DA_EXTERNAL_VOLUME_REQUIRED:-false}
  build_cache:
    name: build
    external: false
  deps_cache:
    name: deps
    external: false
