---
apiVersion: v1
kind: Service
metadata:
  name: toolbox
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: toolbox
    port: 1312
  selector:
    app: toolbox
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  ports:
  - name: db 
    port: 5432
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet 
metadata:
  name: toolbox
spec:
  replicas: 2
  serviceName: toolbox
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - toolbox 
            topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: docker
      containers:
        - name: toolbox
          imagePullPolicy: Always
          image: docker.pkg.github.com/distributeaid/toolbox/toolbox:latest
          ports:
            - name: toolbox
              containerPort: 1312
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_PORT
              value: "5432"
            - name: PORT
              value: "1312"
            - name: ENV
              value: dev
            - name: TOOLBOX_VERSION
              value: "{{VERSION}}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db 
  template:
    metadata:
      labels:
        app: db 
    spec:
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db-pv-claim
      containers:
        - name: db 
          image: postgres:11.2
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pv-claim
  labels:
    app: db
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi