apiVersion: apps/v1
kind: Deployment
metadata:
  name: db 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db 
  template:
    metadata:
      labels:
        app: db 
    spec:
      containers:
        - name: db 
          image: postgres:11.2
          ports:
            - name: http
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: toolbox
            - name: POSTGRES_USER
              value: toolbox
            - name: POSTGRES_PASSWORD
              value: toolbox