apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      containers:
        - name: toolbox
          image: pedrogutierrez/toolbox:latest
          ports:
            - name: http
              containerPort: 1312
              protocol: TCP
          env:
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_DB
              value: toolbox
            - name: POSTGRES_USER
              value: toolbox
            - name: POSTGRES_PASSWORD
              value: toolbox
            - name: POSTGRES_PORT
              value: "5432"
            - name: PORT
              value: "1312"
            - name: MIX_ENV
              value: dev
            - name: ENV
              value: dev
          livenessProbe:
            httpGet:
              path: /health
              port: 1312
          readinessProbe:
            httpGet:
              path: /health
              port: 1312