export const initialValues = {
  name: '',
  slug: '',
  country: '',
  state: '',
  province: '',
  postalCode: '',
  description: '',
  requestForm: '',
  requestFormResults: '',
  donationForm: '',
  donationFormResults: '',
  volunteerForm: '',
  volunteerFormResults: '',
}
