stages:
  - build ci image
  - stylecheck
  - test
  - deploy_staging
  - deploy_production

include:
  - local: .gitlab/elixir.gitlab-ci.yml

# # Good overview of GitLab CI setup: https://blog.el-chavez.me/2017/07/13/elixir-phoenix-gitlabci/
# variables:
#   POSTGRES_USER: toolbox
#   POSTGRES_PASSWORD: "1312"
#   POSTGRES_DB: toolbox_test
#   DB_HOSTNAME_TEST: dbtest
#   MIX_ENV: "test"

# # This file is a template, and might need editing before it works on your project.
# image: elixir:latest


# before_script:
#   - apt-get update && apt-get -y install postgresql-client
#   - mix local.hex --force
#   - mix local.rebar --force
#   - mix deps.get --only test
#   - mix ecto.reset

# # Pick zero or more services to be used on all builds.
# # Only needed when using a docker container to run your tests in.
# # Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
# services:
#   - name: postgres:11.2
#     alias: dbtest

# mix:
#   script:
#   - mix test
#   - mix coveralls
