# CI FILE FOR lib/
build-image elixir:
  extends: .elixir
  stage: build ci image
  image: docker:stable
  services:
      - docker:dind
  before_script:
    - apk upgrade -ql ; apk add -ql python3
    - pip3 install -q awscli
    - docker info
    - docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - docker build -t $GITLAB_CONTAINER_TEST_IMAGE -f web.Dockerfile .
    - docker push $GITLAB_CONTAINER_TEST_IMAGE
    - echo $(aws ecr get-login-password) | docker login --username AWS --password-stdin 299303747484.dkr.ecr.us-east-2.amazonaws.com
    - docker build -t $ECR_CONTAINER_TEST_IMAGE -f web.Dockerfile .
    - docker push $ECR_CONTAINER_TEST_IMAGE

test elixir:
  extends: .elixir
  stage: test
  image: ${GITLAB_CONTAINER_TEST_IMAGE}
  services:
    - name: postgres:11.2
      alias: dbtest
  script:
    - apt-get update && apt-get -y install postgresql-client
    - mix local.hex --force
    - mix local.rebar --force
    - mix deps.get --only test
    - mix ecto.reset
    - mix test
    - mix coveralls
