.elixir:
  variables:
    PROJECT_NAME: lib
    POSTGRES_USER: toolbox
    POSTGRES_PASSWORD: "1312"
    POSTGRES_DB: toolbox_test
    DB_HOSTNAME_TEST: dbtest
    MIX_ENV: "test"
  variables:
    PROJECT_NAME: lib

.react:
  variables:
    DUMMY: dummy
