cache:
  key: ${CI_JOB_NAME}
variables:
    DOCKER_DRIVER: overlay2
    DOCKER_VERSION: "19.03.8"
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ''

.elixir:
  variables:
    PROJECT_NAME: lib
    POSTGRES_USER: toolbox
    POSTGRES_PASSWORD: "1312"
    POSTGRES_DB: toolbox_test
    DB_HOSTNAME_TEST: dbtest
    MIX_ENV: "test"
    ECR_CONTAINER_TEST_IMAGE: 299303747484.dkr.ecr.us-east-2.amazonaws.com/masksfordocs/toolbox/ci/elixir:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
    GITLAB_CONTAINER_TEST_IMAGE: ${CI_REGISTRY_IMAGE}/ci/elixir:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}

.ui:
  variables:
    REACT_DIR: ./react_ui
    ECR_CONTAINER_TEST_IMAGE: 299303747484.dkr.ecr.us-east-2.amazonaws.com/masksfordocs/toolbox/ci/ui:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
    GITLAB_CONTAINER_TEST_IMAGE: ${CI_REGISTRY_IMAGE}/ci/ui:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}
