.elixir:
<<<<<<< HEAD
  variables:
    PROJECT_NAME: lib
    POSTGRES_USER: toolbox
    POSTGRES_PASSWORD: "1312"
    POSTGRES_DB: toolbox_test
    DB_HOSTNAME_TEST: dbtest
    MIX_ENV: "test"
=======
  only:
    variables:
      - $PIPELINE_NAME =~ /lib/
  variables:
    PROJECT_NAME: lib

.cleanup:
  only:
    variables:
      - $PIPELINE_NAME == "cleanup"
>>>>>>> trying different image build
