# CI FILE FOR react_ui

# variables:
#   CONTAINER_TEST_IMAGE: ${CI_REGISTRY_IMAGE}/ci/ui:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}

# This file is a template, and might need editing before it works on your project.
# image: elixir:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service

# build ci image:
#   extends: .react
#   stage: build ci image
#   image: docker:stable
#   services:
#       - docker:dind
#   before_script:
#     - docker info
#     - docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
#   script:
#     - docker build -t $CONTAINER_TEST_IMAGE -f ui.Dockerfile .
#     - docker push $CONTAINER_TEST_IMAGE

test react:
  extends: .react
  stage: test
  image: ${CONTAINER_TEST_IMAGE}
  script:
    - cd ${REACT_DIR}
    - npm install 
    - npm run lint
    - npm test
