# CI FILE FOR react_ui
prepare_ui:
  extends: .ui
  stage: prepare
  script:
    - "true"

build_ui:
  extends: .ui
  stage: build
  needs: ["prepare_ui"]
  image: node:13.12.0-alpine3.11
  artifacts:
    expire_in: 1 day
    expose_as: "npm-build"
    paths:
      - ${REACT_DIR}/
      - etc/nginx/conf.d
  script:
    - cd ${REACT_DIR}
    - npm install
    - npm install react-scripts
    - npm run lint
    - npm run-script build

unit_test_ui:
  extends: .ui
  stage: unit_test
  needs: ["build_ui"]
  image: node:13.12.0-alpine3.11
  script:
    - cd ${REACT_DIR}
    - npm test

image_ui:
  extends: .ui
  stage: image
  needs: ["build_ui", "unit_test_ui"]
  image: docker:${DOCKER_VERSION}
  services:
    - docker:${DOCKER_VERSION}-dind
  before_script:
    - apk upgrade -ql ; apk add -ql python3
    - pip3 install -q awscli
    - rm .dockerignore
    - docker info
  script:
    - docker build -t $ECR_CONTAINER_TEST_IMAGE -f ui.Dockerfile .
    - echo $(aws ecr get-login-password) | docker login --username AWS --password-stdin 299303747484.dkr.ecr.us-east-2.amazonaws.com
    - docker push $ECR_CONTAINER_TEST_IMAGE
