# CI FILE FOR react_ui
prepare_ui:
  extends: .ui
  stage: prepare
  script:
    - "true"

build_ui:
  extends: .ui
  stage: build
  needs: ["prepare_ui"]
  image: node:13.12.0-alpine3.11
  artifacts:
    expire_in: 1 day
    expose_as: "npm-build"
    paths:
      - ${REACT_DIR}/build
      - etc/nginx/conf.d
  script:
    - cd ${REACT_DIR}
    - npm config set registry https://gitlab.com/api/v4/packages/npm/
    - npm install
    - npm install react-scripts
    - npm run lint
    - npm run-script build

unit_test_ui:
  extends: .ui
  stage: unit_test
  needs: ["build_ui"]
  image: node:13.12.0-alpine3.11
  cache:
    policy: pull
  script:
    - cd ${REACT_DIR}
    - npm config set registry https://gitlab.com/api/v4/packages/npm/
    - npm test

cypress_e2e:
  extends: .ui
  stage: e2e_test
  needs: ["build_ui"]
  image: cypress/base:10
  cache:
    policy: pull
  script:
    - cd ${REACT_DIR}
    #- npm config set registry https://gitlab.com/api/v4/packages/npm/
    - npm ci
    # show where the Cypress test runner binaries are cached
    - $(npm bin)/cypress cache path
    # show all installed versions of Cypress binary
    - $(npm bin)/cypress cache list
    - $(npm bin)/cypress verify
    - npm run cypress:ci

image_ui:
  extends: .ui
  stage: image
  needs: ["build_ui", "unit_test_ui"]
  image: docker:${DOCKER_VERSION}
  cache: {}
  services:
    - docker:${DOCKER_VERSION}-dind
  before_script:
    - apk upgrade -ql ; apk add -ql python3
    - pip3 install -q awscli
    - rm .dockerignore
    - docker info
  script:
    - docker build -t $ECR_CONTAINER_TEST_IMAGE -f ui.Dockerfile .
    - echo $(aws ecr get-login-password) | docker login --username AWS --password-stdin 299303747484.dkr.ecr.us-east-2.amazonaws.com
    - docker push $ECR_CONTAINER_TEST_IMAGE
