# CI FILE FOR react_ui
build-image ui:
  extends: .ui
  stage: build ci image
  image: docker:stable
  services:
      - docker:dind
  before_script:
    - apk upgrade -ql ; apk add -ql python3
    - pip3 install -q awscli
    - docker info
    - docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
  script:
    - docker build -t $GITLAB_CONTAINER_TEST_IMAGE -f ui.Dockerfile .
    - docker push $GITLAB_CONTAINER_TEST_IMAGE
    - echo $(aws ecr get-login-password) | docker login --username AWS --password-stdin 299303747484.dkr.ecr.us-east-2.amazonaws.com
    - docker build -t $ECR_CONTAINER_TEST_IMAGE -f ui.Dockerfile .
    - docker push $ECR_CONTAINER_TEST_IMAGE

test ui:
  extends: .ui
  stage: test
  image: ${GITLAB_CONTAINER_TEST_IMAGE}
  script:
    - cd ${REACT_DIR}
    - npm install
    - npm run lint
    - cp src/aws-exports.ci.js src/aws-exports.js
    - npm test
