// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-east-2",
  "aws_cognito_identity_pool_id": "",
  "aws_cognito_region": "us-east-2",
  "aws_user_pools_id": "",
  "aws_user_pools_web_client_id": "",
  "oauth": {}
};


export default awsmobile;