name: ci 
on:
  push: {}
  schedule: 
    - cron:  '0 2 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: toolbox
          POSTGRES_PASSWORD: toolbox 
          POSTGRES_DB: toolbox 
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      MIX_ENV: test
      POSTGRES_USER: toolbox
      POSTGRES_PASSWORD: toolbox
      POSTGRES_DB: toolbox
      DB_HOSTNAME_TEST: toolbox
      POSTGRES_PORT: 5432
    steps:
      - uses: actions/checkout@v2
      - run: mix local.rebar --force
      - run:  mix local.hex --force
      - run: mix deps.get
      - run: mix test
  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: pedrogutierrez/toolbox
        tags: latest
  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: Deploy
      uses: pedro-gutierrez/elementary-action@v5
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}