name: ci 
on:
  push: {}
  schedule: 
    - cron:  '0 2 * * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: docker exec -it toolbox mix test
  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Docker image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: pedrogutierrez/toolbox
        tags: latest
  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: Deploy
      uses: pedro-gutierrez/elementary-action@v5
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}