name: ci 
on:
  push: {}
  schedule: 
    - cron:  '0 2 * * *'
jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   services:
  #     postgres:
  #       image: postgres:11
  #       env:
  #         POSTGRES_USER: toolbox
  #         POSTGRES_PASSWORD: toolbox 
  #         POSTGRES_DB: toolbox 
  #       ports:
  #       - 5432:5432
  #       options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
  #   env:
  #     MIX_ENV: test
  #     POSTGRES_USER: toolbox
  #     POSTGRES_PASSWORD: toolbox
  #     POSTGRES_DB: toolbox
  #     DB_HOSTNAME_TEST: localhost
  #     POSTGRES_PORT: 5432
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup Elixir
  #       uses: actions/setup-elixir@v1.0.0
  #       with:
  #         otp-version: 22.2.6
  #         elixir-version: 1.10.1
  #     - name: Setup rebar
  #       run: mix local.rebar --force
  #     - name: Setup Hex
  #       run: mix local.hex --force
  #     - name: Fetch dependencies
  #       run: mix deps.get
  #     - name: Compile and test
  #       run: mix test
  #     - name: If errors, notify 
  #       if: failure()
  #       uses: craftech-io/slack-action@v1
  #       with:
  #         slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
  #         status: failure
  package:
    runs-on: ubuntu-latest
    #needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build and push Docker image
      uses: pedro-gutierrez/docker-action@v9
      with:
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: latest
    - name: If errors, notify 
      if: failure()
      uses: craftech-io/slack-action@v1
      with:
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        status: failure
  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: Deploy
      uses: pedro-gutierrez/elementary-action@v6
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - name: If errors, notify 
      if: failure()
      uses: craftech-io/slack-action@v1
      with:
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        status: failure
    - name: If success, notify 
      if: success()
      uses: craftech-io/slack-action@v1
      with:
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        status: success