name: ci 
on:
  push: {}
  schedule: 
    - cron:  '0 2 * * *'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: pedrogutierrez/toolbox
        tags: latest
    - name: Deploy
      uses: pedro-gutierrez/elementary-action@v5
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}